version: "3.8"
services:
  expenseapp:
    image: 'expenseapp:v3'
    networks:
      - 'expenseapp-network'
    ports:
      - '8080:8080'
    depends_on:
      - postgresdb
  postgresdb:
    image: 'postgres:14.11-alpine'
    networks:
      - 'expenseapp-network'
    volumes:
      - expenseapp_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mukesh
      POSTGRES_PASSWORD: mukesh@123

volumes:
  expenseapp_pgdata:
networks:
  expenseapp-network:



